### ISSUE TITLE
on extended second screen stuck in lower edge

### ISSUE THREAD

**Issue by Konfekt** [4strid/vim_mouse_2.ahk#2]
On a single screen your application works wonderfully, but once the mouse cursor reaches another extended screen it goes downwards to the edge of the screen and is stuck there; no way to move the cursor anymore in normal mode.

**Comment by 4strid** [comment]
i did notice this when using a friend's computer recently ... i am not sure why this happens . i'm sure i used to use this on a multimonitor system with both 2 and 3 screens with no hitches when i was a developer .

**Comment by 4strid** [comment]
(fat thumbed close button)

**Comment by 4strid** [comment]
one thing i can think of is that i always had my first 2 monitors slightly offset vertically , which may have masked the bug .

i don't have good access to a windows machine any more to test this on , but i will attempt a patch nonetheless .

**Comment by Konfekt** [comment]
I cannot reproduce that it works on two screens with either vertical offset (first screen below/above the other one) between them

**Comment by 4strid** [comment]
awesome discovery  !  but uh . ummm . well , i assume this is still a problem for you though ?  i may have access to a Windows PC soon and can try and come up with a version using MoveMouseToMonitor and accounting for scaling  . Any idea how we can figure out what the scaling is ?...

**Comment by Konfekt** [comment]
Apparently there is a built-in [variable](https://www.autohotkey.com/boards/viewtopic.php?t=40892) to figure out the DPI scaling.

**Comment by 4strid** [comment]
huh . turns out it was a 1-line fix  xD . . . i thought i was going to have to gut the whole thing and manually deal with per-monitor DPI  , but on a whim , i decided to just throw that line in and **presto**

**Comment by Konfekt** [comment]
Wow, thank you very much!
