### ISSUE TITLE
ToggleInsert/NormalMode

### ISSUE THREAD

**Issue by Konfekt** [4strid/vim_mouse_2.ahk#3]
Could a single key combination be bound to switch between Insert and Normal mode? Say `Ctrl+;` like Keynav does.

**Comment by 4strid** [comment]
Shift+Capslock is presently the shortcut for toggling modes . I can add another shortcut for toggling modes since this doesn't seem to work for you due to key conflicts .

**Comment by Konfekt** [comment]
Okay, thank you, I overlooked it probably as it is bound in two places (corresponding to the two modes).
