### ISSUE TITLE
make key combinations customizable

### ISSUE THREAD

**Issue by Konfekt** [4strid/vim_mouse_2.ahk#4]
Some already rebind CapsLock for other autohotkey scripts, or use it as Escape, Control key, or both. Therefore, the used mappings could be set at the start of the AHK file.

**Comment by 4strid** [comment]
As far as i am aware , functions are not hoisted in AHK so moving the bindings to the top is not possible . If you are unhappy with any of the bindings , you are free to simply edit the .ahk

**Comment by 4strid** [comment]
(friggin close button again) ... file and change any bindings you dislike . closing for now as i think simply adding alternate bindings from Capslock solves the actual issue ( see #3 )

**Comment by Konfekt** [comment]
Yes, thank you, that is what I did, it only entails merge conflicts once the repo is updated.

**Comment by Konfekt** [comment]
For example, a user config AHK file could be [sourced](https://github.com/pmb6tz/windows-desktop-switcher).

**Comment by Konfekt** [comment]
For what it's worth, I use [these simplified key bindings](https://gist.github.com/Konfekt/b2efadb9c8d20b67d8bbe358f51c33a5/revisions) to emulate those of keynav.
